In [2]:
import numpy as np  
import pandas as pd
from sklearn import svm
from sklearn.model_selection import GridSearchCV
df11 = pd.read_csv('subject101.csv',delimiter=',')
df12 = pd.read_csv('subject102.csv',delimiter=',')
df13 = pd.read_csv('subject103.csv',delimiter=',')
df14 = pd.read_csv('subject104.csv',delimiter=',')
df15 = pd.read_csv('subject105.csv',delimiter=',')
df16 = pd.read_csv('subject106.csv',delimiter=',')
df17 = pd.read_csv('subject107.csv',delimiter=',')
df18 = pd.read_csv('subject108.csv',delimiter=',')
df19 = pd.read_csv('subject109.csv',delimiter=',')
# print df.shape








set([30.375, 1.0, 32.1875, -0.020804200000000002, -1.75247, 9.74041, -58.3656, 0.00600704, 5.744669999999999, 0.200711, 8.14592, -0.00953821, 0.90499, -0.024303900000000003, 0.020881999999999998, 9.58649, -0.059842599999999996, 0.250816, 0.129092, 37.67, 30.75, 5.78739, 9.69762, 43.5427, -36.3197, 0.0254788, -67.9584, 7.67288, 9.6498, -20.9091, -1.6504299999999998, -60.8916, -1.47329, 0.000944724, 100.0, 9.583, 2.27373, -50.508, -1.88438, -0.17171, 0.0193427, 2.29196])


set([1, 2, 3, 4, 5, 6, 7, 12, 13, 16, 17, 24])


# intensity:

In [19]:
def std(df):
    data_std=[] 
    note = 0
    for i in range(1,len(df)):
        if df.iloc[i,1] != df.iloc[i-1,1]:
            period = i-1 - note
            step = 50
            times = period//step
            for j in range(times):
                std = df.iloc[note+50*j:note+50*(j+1),1:].std()
                std.iloc[0] = df.iloc[i-1,1]
                data_std.append(std.values)
            note = i
            print "lable change: %s to %s" %(df.iloc[i-1,1], df.iloc[i,1])
    return pd.DataFrame(data_std)
set11 = std(df11)
set12 = std(df12)
set13 = std(df13)
set14 = std(df14)
set15 = std(df15)
set16 = std(df16)
set17 = std(df17)
set18 = std(df18)
set19 = std(df19)


lable change: 1 to 2
lable change: 2 to 3
lable change: 3 to 17
lable change: 17 to 16
lable change: 16 to 12
lable change: 12 to 13
lable change: 13 to 12
lable change: 12 to 13
lable change: 13 to 4
lable change: 4 to 7
lable change: 7 to 6
lable change: 6 to 5
lable change: 5 to 24
lable change: 1 to 2
lable change: 2 to 3
lable change: 3 to 17
lable change: 17 to 16
lable change: 16 to 12
lable change: 12 to 13
lable change: 13 to 12
lable change: 12 to 13
lable change: 13 to 4
lable change: 4 to 7
lable change: 7 to 6
lable change: 6 to 5
lable change: 5 to 24
lable change: 1 to 2
lable change: 2 to 3
lable change: 3 to 17
lable change: 17 to 16
lable change: 16 to 13
lable change: 13 to 12
lable change: 12 to 13
lable change: 13 to 12
lable change: 12 to 13
lable change: 13 to 4
lable change: 1 to 2
lable change: 2 to 3
lable change: 3 to 17
lable change: 17 to 16
lable change: 16 to 12
lable change: 12 to 13
lable change: 13 to 12
lable change: 12 to 13
lable change: 13 to 4
lab

In [20]:
df = pd.concat([set11,set12,set13,set14,set15,set16,set17,set18,set19])
df.loc[df.iloc[:,0].isin ([1,2,3,17])] = 0
df.loc[df.iloc[:,0].isin ([16,13,4,7,6])] = 1
df.loc[df.iloc[:,0].isin ([12,5,24])] = 2
print df.shape
print set(df.iloc[:,0])

(37161, 41)
set([0.0, 1.0, 2.0])


In [21]:
from sklearn.model_selection import train_test_split
X = df.iloc[:,1:]
y = df.iloc[:,0]
X_train, X_test, y_train, y_test = train_test_split(X, y,train_size=0.8, shuffle = True,stratify=y)
def norm(df):
    df_norm = (df - df.mean()) / (df.max() - df.min())
    return df_norm
X_train = norm(X_train)
X_test = norm(X_test)
clf = svm.LinearSVC(penalty='l1',dual=False)
parameters = {'C':np.logspace(-10, 10, num=10, base=2)}
grid = GridSearchCV(clf,parameters,cv=10)
grid.fit(X_train,y_train)
print grid
print clf
print grid.best_params_
print grid.score(X_test,y_test)


GridSearchCV(cv=10, error_score='raise',
       estimator=LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0),
       fit_params=None, iid=True, n_jobs=1,
       param_grid={'C': array([9.76562e-04, 4.55675e-03, 2.12623e-02, 9.92126e-02, 4.62937e-01,
       2.16012e+00, 1.00794e+01, 4.70315e+01, 2.19454e+02, 1.02400e+03])},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)
LinearSVC(C=1.0, class_weight=None, dual=False, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l1', random_state=None, tol=0.0001,
     verbose=0)
{'C': 0.004556754060844206}
1.0


In [17]:
from sklearn.metrics import hamming_loss
from sklearn.metrics import accuracy_score
# hamming_loss(y_true, y_pred)
# accuracy_score(y_true, y_pred)

# used in evaluating multilabel classification 

y_true = np.array(y_test)
y_pred = grid.predict(X_test)

hamming_loss_value = np.sum(np.not_equal(y_true, y_pred))/float(y_true.size)
accuracy_score_value = grid.score(X_test,y_test)

print 'hamming loss'
print hamming_loss_value
print 'exact match score'
print accuracy_score_value

hamming loss
0.0
exact match score
1.0


In [18]:
from sklearn import metrics
from sklearn.metrics import roc_curve, auc
import matplotlib.pyplot as plt
from sklearn.preprocessing import label_binarize
from scipy import interp


y_true = y_test
y_pred = grid.predict(X_test)
y_hat = grid.decision_function(X_test)


print(metrics.confusion_matrix(y_true, y_pred))
print("misclassification")
print(1-grid.score(X_test,y_test))

[[1609    0    0]
 [   0 1681    0]
 [   0    0  422]]
misclassification
0.0
